package main

import "testing"

func Test_part1(t *testing.T) {
	type args struct {
		s      string
		factor int
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{"1", args{`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 2}, 374},
		{"10", args{`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 10}, 1030},
		{"100", args{`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 100}, 8410},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := sumDistances(tt.args.s, tt.args.factor); got != tt.want {
				t.Errorf("part1() = %v, want %v", got, tt.want)
			}
		})
	}
}
